# SPDX-FileCopyrightText: 2024 NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

version = 1
SPDX-PackageName = "gtfs2netex-api"
SPDX-PackageSupplier = "NOI Techpark <digital@noi.bz.it>"
SPDX-PackageDownloadLocation = "https://github.com/noi-techpark/gtfs2netex-api"

[[annotations]]
path = [".github/**", "infrastructure/**", "README.md", ".gitignore", ".gitmodules", ".pre-commit-config.yaml", "src/go.mod", "src/go.sum", "calls.http"]
precedence = "aggregate"
SPDX-FileCopyrightText = "(c) NOI Techpark <digital@noi.bz.it>"
SPDX-License-Identifier = "CC0-1.0"
