name: CI/CD

on:
  push:
    tags: [v*]

env:
  PROJECT_NAME: gtfs2netex-api
  DOCKER_IMAGE: ghcr.io/${{ github.repository }}/${{ github.event.repository.name }}
  DOCKER_TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: true
          
      - name: Build and push images
        uses: noi-techpark/github-actions/docker-build-and-push@v2
        with:
          docker-username: ${{ github.actor }}
          docker-password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Add a "unstable" docker tag
        uses: shrink/actions-docker-registry-tag@v2
        with:
          registry: ghcr.io
          repository: ${{ env.DOCKER_IMAGE }}
          target: ${{ env.DOCKER_TAG }}
          tags: |
            latest
            ${{ github.ref_name }}
          
